name: EKS Runner Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted]

    steps:
      - name: Print Host Info
        run: |
          echo "Running on EKS Runner"
          hostname
          uname -a