name: EKS Runner Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, eks-runner]

    steps:
      - name: Print Host Info
        run: |
          echo "Running on EKS Runner"
          hostname
          uname -a